notifications:
    email:
        on_success: change
        on_failure: change
language: minimal
env:
    global:
        - SSH_DEPLOY_KEY_PATH=deploy/deploy_key
        - DEPLOY_SERVER_HOST=vps632104.ovh.net
stages:
    - deploy
jobs:
    include:
        -   stage: deploy
            if: branch = master
            name: deploy
            before_install:
                - openssl aes-256-cbc -K $encrypted_bab5b73fa2a2_key -iv $encrypted_bab5b73fa2a2_iv
                    -in ${SSH_DEPLOY_KEY_PATH}.enc -out ${SSH_DEPLOY_KEY_PATH} -d
                - eval "$(ssh-agent -s)"
                - chmod 600 ${SSH_DEPLOY_KEY_PATH}
                - echo -e "Host ${DEPLOY_SERVER_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
                - ssh-add ${SSH_DEPLOY_KEY_PATH}
            script:
                - ssh -i ${SSH_DEPLOY_KEY_PATH} root@${DEPLOY_SERVER_HOST} "echo 'Connected, Hello
                    !!!! '; hostname"
                - scp -i ${SSH_DEPLOY_KEY_PATH} deploy/deploy.sh root@${DEPLOY_SERVER_HOST}:deploy/supervision/deploy.sh
                - ssh -i ${SSH_DEPLOY_KEY_PATH} root@${DEPLOY_SERVER_HOST} "bash deploy/supervision/deploy.sh"
