version: '3'

services:
    portainer:
        image: portainer/portainer-ce
        command: '-H unix:///var/run/docker.sock'
        restart: always
        ports:
            - '9000:9000'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/var/portainer/data:/data'
