version: '3'

services:
    portainer:
        container_name: portainer
        image: portainer/portainer-ce
        environment:
            - VIRTUAL_HOST=portainer.418.ovh
            - VIRTUAL_PORT=9000
        command: '-H unix:///var/run/docker.sock'
        restart: always
        ports:
            - '80:9000'
        networks:
            - network-proxy
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/var/portainer/data:/data'
networks:
    network-proxy:
        external:
            name: network-proxy
